name=MLLSoundTiny
version=1.0.0
author=Jueff
maintainer=Jueff <mobaledlib@gmx.at>
sentence=<h3>The library bundles ATTiny protocol compatible sound related classes for MobaLedLib</h3>
paragraph=MLLSoundTiny is an Arduino library for controlling sound modules, particularly for integration with LED data in model railway applications. It enables processing of LED signals, mapping them to sound commands, and managing multiple sound modules via serial interfaces.
category=Signal Input/Output
url=https://github.com/Jueff/MLLSoundTiny
architectures=rp2040
includes=LedToSound.h,MLLSoundTiny.h,SoundModule.h,MultiPlayer.h
depends=PicoFlashStorage