name=MLLSoundTiny
version=0.1.0
author=Jueff
maintainer=Jueff <mobaledlib@gmx.at>
sentence=<h3>The library bundles ATTiny compatible sound related classes for MobaLedLib</h3>
paragraph=0.1 release
category=Signal Input/Output
url=https://github.com/Jueff/MLLSoundTiny
architectures=rp2040
includes=LedToSound.h,MLLSoundTiny.h,SoundModule.h 
depends=PicoFlashStorage