name=MLLSoundTiny
version=1.0.0
author=Jueff
maintainer=Jueff <mobaledlib@gmx.at>
sentence=<h3>The library bundles ATTiny protocol compatible sound related classes for MobaLedLib</h3>
category=Signal Input/Output
url=https://github.com/Jueff/MLLSoundTiny
architectures=rp2040
includes=LedToSound.h,MLLSoundTiny.h,SoundModule.h,MultiPlayer.h
depends=PicoFlashStorage